sensors:
  logical_camera_0:
    type: logical_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [3.082385, -1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_3:
    type: logical_camera
    pose:
      xyz: [5, -1.750927, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_4:
    type: logical_camera
    pose:
      xyz: [-0.2, 2.2, 1.6]
      rpy: ['pi/2', 'pi/2', 0]

  logical_camera_5:
    type: logical_camera
    pose:
      xyz: [-3.75, 3, 2.49]
      rpy: ['pi/2', 'pi/2', 0]

  logical_camera_6:
    type: logical_camera
    pose:
      xyz: [-3.75, 0, 2.49]
      rpy: ['pi/2', 'pi/2', 0]

  logical_camera_7:
    type: logical_camera
    pose:
      xyz: [0, 7.25, 1.7]
      rpy: ['pi/2', 'pi/2', 0]

  logical_camera_8:
    type: logical_camera
    pose:
      xyz: [0, -7.25, 1.7]
      rpy: ['pi/2', 'pi/2', 0]
